export default [
  {
    name: 'moonGue',
    dayScore: 400,
    monthScore: 500,
    generalScore: 4500,
  },
  {
    name: 'adinow',
    dayScore: 100,
    monthScore: 500,
    generalScore: 3500,
  },
  {
    name: 'adi',
    dayScore: 200,
    monthScore: 600,
    generalScore: 1500,
  },
  {
    name: 'AlexEnder',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
  {
    name: 'Name',
    dayScore: 50,
    monthScore: 80,
    generalScore: 2400,
  },
]
